### ISSUE TITLE
Does this subscribe to snapshot of firestore data ? will it set state of data variable everytime there is update in firestore ?

### ISSUE THREAD

**Issue by suhashollakc** [armedi/makefire#1]

**Comment by suhashollakc** [comment]
import React, { Component } from 'react'
import db from '../firestore'
import makefire from 'makefire';
import DataTable from 'react-data-table-component';
import DataTableExtensions from 'react-data-table-component-extensions';
import '../Report.css'
import history from '../components/History'

const {useDocument, useCollection} = makefire(db);

  // subscribing to 'users' collection
  const { data, loading, error } = useCollection('Admin_Transactions')


  const columns = [
    {name:'Date', selector:'date', sortable: true,},
    {name:'Type',selector:'type', sortable: true,},
    {name:'Employee Name',selector: 'employee_id', sortable: true,},
    {name:'VDSL',selector:'vdsl', sortable: true,},
    {name:'Huawei',selector:'huawei', sortable: true,},
    {name:'Nokia',selector:'nokia', sortable: true,},
    {name:'VDSL 100 MBPS',selector:'vdsl_100mbps', sortable: true,},
    {name:'Cable DropWire',selector:'cable_copper_dropwire', sortable: true,},
    {name:'Cable 10 Pair',selector:'cable_10_pairs', sortable: true,},
    {name:'Cable 5 Pair',selector:'cable_5_pairs', sortable: true,},
    {name:'Cable Indoor',selector:'cable_indoor', sortable: true,},
    {name:'Cable Outdoor',selector:'cable_outdoor', sortable: true,},
    {name:'Pole Anchor',selector:'pole_anchor', sortable: true,},
    {name:'Patch Cord',selector:'patch_cord', sortable: true,},
    {name:'Rosset',selector:'rosset', sortable: true,},
    {name:'Module',selector:'module', sortable: true,},
    {name:'Face Flat',selector:'face_flat', sortable: true,},
    
    ];
    // const data = Object.keys(data).map(i=> data[i]);

const tableData = {
 columns,
 data,
}

export class DailyReport extends Component {

    render() {
        return (
             <div class='InventoryReportInstallation'>
             
    <div className="report-card">
    <button className="btn btn-back" onClick={() => history.goBack()}>&#8592;  Back</button>
   <DataTableExtensions {...tableData} exportHeaders= {true}>
   <DataTable
    title="Inventory Report(Installation)"
      defaultSortField="date"
      defaultSortAsc={false}
      pagination
      highlightOnHover
      fixedHeader = {true}
    />
   </DataTableExtensions>
   
    
    </div>
    

          </div>
        )
    }
}

export default DailyReport

**Comment by suhashollakc** [comment]
Kindly assist me the right way to use

**Comment by armedi** [comment]
Yes, this library will subscribe to changes firestore data by changing state everytime an update happen.

To use this library you should use function component. As from the code snippet you provided, I see that you are using class component. The hook can only be used inside a function component.

For reference: [https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions)
